# Generated by Django 4.2.29 on 2026-03-11 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/')),
                ('bio', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('listings_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('plot', 'Plot / Land'), ('penthouse', 'Penthouse'), ('commercial', 'Commercial'), ('office', 'Office Space'), ('shop', 'Shop / Showroom'), ('warehouse', 'Warehouse')], max_length=20)),
                ('purpose', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease')], default='sale', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('under_offer', 'Under Offer'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('locality', models.CharField(max_length=150)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_negotiable', models.BooleanField(default=False)),
                ('maintenance_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('balconies', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking_spots', models.PositiveSmallIntegerField(default=0)),
                ('floor_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('built_up_area', models.DecimalField(decimal_places=2, help_text='sqft', max_digits=10)),
                ('carpet_area', models.DecimalField(blank=True, decimal_places=2, help_text='sqft', max_digits=10, null=True)),
                ('plot_area', models.DecimalField(blank=True, decimal_places=2, help_text='sqft', max_digits=10, null=True)),
                ('furnishing', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], default='unfurnished', max_length=20)),
                ('facing', models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('ne', 'North-East'), ('nw', 'North-West'), ('se', 'South-East'), ('sw', 'South-West')], max_length=5)),
                ('age_of_property', models.PositiveSmallIntegerField(blank=True, help_text='years', null=True)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_lift', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_clubhouse', models.BooleanField(default=False)),
                ('has_power_backup', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='listings.agent')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.city')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyEnlistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('plot', 'Plot / Land'), ('penthouse', 'Penthouse'), ('commercial', 'Commercial'), ('office', 'Office Space'), ('shop', 'Shop / Showroom'), ('warehouse', 'Warehouse')], max_length=20)),
                ('purpose', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('built_up_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='listings.property')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
